import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from "./partials/Sidebar";
import Content from "./partials/Content";
import Footer from "./partials/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full h-screen">
          <Sidebar />
          <div className="right-container p-4 w-[78%] overflow-y-scroll">
            <Content>{children}</Content>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
